version: "3.9"

services:
  app:
    container_name: ielts_mock_app
    image: ielts_mock
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4012}:4012"
    env_file:
      - ${ENV_FILE:-.env.production}
    environment:
      PORT: 4012
      HOST: 0.0.0.0
    restart: unless-stopped
